#!/usr/bin/env python3
"""Adds the app's `L()` strings to App/Localizable.xcstrings.

Scans `L("key", "English default")` calls, merges the Turkish translations below into the catalog
(existing entries are kept) and lists any key that still lacks a translation, so a new string
cannot ship half-localized by accident.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "App" / "Localizable.xcstrings"
SOURCES = [path for folder in ("App", "Core", "Modules", "Settings") for path in (ROOT / folder).rglob("*.swift")]
CALL = re.compile(r'L\("([^"]+)",\s*"((?:[^"\\]|\\.)*)"\)')

TR = {
    "settings.title": "MyNotch Ayarları",
    "settings.tab.general": "Genel", "settings.tab.modules": "Modüller", "settings.tab.media": "Medya",
    "settings.tab.claude": "Claude", "settings.tab.setup": "Kurulum", "settings.tab.about": "Hakkında",
    "settings.nav.back": "Geri", "settings.nav.forward": "İleri", "settings.copy": "Kopyala",
    # General
    "settings.general.startup": "Başlangıç",
    "settings.general.launchAtLogin": "Oturum açılışında başlat",
    "settings.general.openLoginItems": "Giriş Öğeleri'ni aç…",
    "settings.general.launchFailed": "Giriş öğesi değiştirilemedi",
    "settings.general.notch": "Çentik",
    "settings.general.hoverDelay": "Üzerine gelince açılma süresi",
    "settings.general.closeDelay": "Ayrıldıktan sonra açık kalma süresi",
    "settings.general.closeDelay.help": "İmleç kartın yakınındayken geçerlidir; daha uzağa gidince hemen kapanır.",
    "settings.general.haptics": "Çentik açılırken dokunsal geri bildirim",
    "settings.general.display": "Ekran",
    "settings.general.displayPicker": "Çentiği göster",
    "settings.general.display.automatic": "Otomatik",
    "settings.general.display.disconnected": "%@ (bağlı değil)",
    "settings.general.display.help": "Otomatik, çentikli ekranı; yoksa ana ekranı kullanır. Çentiksiz bir ekranda yüzey üst kenarın altında yüzer.",
    "settings.general.reset": "Varsayılanlara dön",
    "settings.general.launch.enabled": "MyNotch oturum açtığınızda başlar.",
    "settings.general.launch.disabled": "Oturum açtığınızda MyNotch'u menü barında başlat.",
    "settings.general.launch.approval": "Sistem Ayarları → Genel → Giriş Öğeleri'nde onayınız bekleniyor.",
    "settings.general.launch.notFound": "Sistem MyNotch'un bu kopyasını görmüyor. Uygulamalar klasörüne taşıyıp yeniden deneyin.",
    # Modules
    "settings.modules.section": "Modüller",
    "settings.modules.help": "Kapalı bir modül hiçbir şey yapmaz: script yok, ağ isteği yok, açılır bildirim yok. Ekranı kartın altındaki değiştiriciden kalkar.",
    "settings.modules.activity.idle": "Boşta", "settings.modules.activity.live": "Canlı", "settings.modules.activity.urgent": "Uyarı",
    "settings.modules.media.summary": "Spotify ve Müzik'ten çalan parça, eşzamanlı şarkı sözleri, Spotify kitaplığı kalbi.",
    "settings.modules.claude.summary": "Claude Code limitleri, bugünkü harcama ve çalışırken nabız.",
    "settings.modules.demo.summary": "Çentik motorunu dener; yalnızca Debug derlemelerinde.",
    # Media
    "settings.media.missing": "Medya modülü kayıtlı değil.",
    "settings.media.lyrics": "Şarkı sözleri",
    "settings.media.lyrics.enabled": "Eşzamanlı şarkı sözlerini göster",
    "settings.media.lyrics.lead": "Sözler sesin önünde gitsin",
    "settings.media.lyrics.lead.help": "Küçük bir öncelik en iyi okunur. Bluetooth kulaklıklar sesi geciktirir; eksi değer sözleri o kadar geri alır. Oynatıcıdaki ± düğmeleri tek şarkıyı ayarlar.",
    "settings.media.lyrics.forgetShifts": "Şarkı bazlı ayarları unut",
    "settings.media.lyrics.shiftCount": "%lld şarkı",
    "settings.media.lyrics.privacy": "Sözler LRCLIB'den (lrclib.net) gelir. Yalnızca çalan parçanın sanatçısı, adı, albümü ve süresi gönderilir; o da sözler açıkken.",
    "settings.media.spotify": "Spotify kitaplığı",
    "settings.media.spotify.clientID": "Client ID",
    "settings.media.spotify.clientID.prompt": "Spotify Developer Dashboard'daki uygulamanızdan",
    "settings.media.spotify.redirect": "Redirect URI",
    "settings.media.spotify.connect": "Bağlan…",
    "settings.media.spotify.disconnect": "Bağlantıyı kes",
    "settings.media.spotify.dashboard": "Spotify Developer Dashboard",
    "settings.media.spotify.privacy": "Dashboard'da ücretsiz bir uygulama oluşturun, client ID'sini buraya yapıştırın ve yukarıdaki redirect URI'yi ekleyin. Spotify'a yalnızca çalan parçanın kimliği gönderilir; o da bağlıyken. Token'lar Application Support'ta yalnızca sizin okuyabildiğiniz bir dosyada durur.",
    "settings.media.spotify.notConfigured": "Kalbi açmak için bir client ID girin",
    "settings.media.spotify.disconnected": "Bağlı değil",
    "settings.media.spotify.connecting": "Tarayıcınızda Spotify bekleniyor…",
    "settings.media.spotify.connected": "Bağlı — kalp kitaplığınızı yansıtır",
    "settings.media.automation": "Otomasyon izni",
    "settings.media.automation.open": "Gizlilik Ayarları'nı aç…",
    "settings.media.automation.check": "Yeniden denetle",
    "settings.media.automation.help": "MyNotch, Spotify ve Müzik'e ne çaldığını AppleScript ile sorar. macOS izin istemini bir oynatıcı ilk kez çalışırken gösterir.",
    "settings.media.automation.unknown": "Henüz sorulmadı — Spotify ya da Müzik'i başlatın",
    "settings.media.automation.granted": "Spotify ve Müzik için izin verildi",
    "settings.media.automation.denied": "Reddedildi — Otomasyon altında MyNotch'a izin verip yeniden denetleyin",
    # Claude
    "settings.claude.missing": "Claude modülü kayıtlı değil.",
    "settings.claude.account": "Hesap",
    "settings.claude.lastReading": "Son okuma",
    "settings.claude.refresh": "Şimdi yenile",
    "settings.claude.account.help": "Claude Code'un Keychain'de sakladığı token yalnızca okunur — asla yazılmaz, yenilenmez ya da loglanmaz. Giriş ve çıkış `claude` komutuyla yapılır.",
    "settings.claude.alerts": "Uyarılar",
    "settings.claude.alerts.enabled": "Bir limit eşiği aşınca açılır bildirim",
    "settings.claude.alerts.warning": "Uyarı eşiği",
    "settings.claude.alerts.critical": "Kritik eşik",
    "settings.claude.alerts.reset": "Eşikleri sıfırla",
    "settings.claude.alerts.help": "Her pencere her eşiği bir kez duyurur; halkalar aynı noktalarda turuncuya ve kırmızıya döner.",
    "settings.claude.polling": "Sorgulama",
    "settings.claude.polling.interval": "Anthropic'e sorma sıklığı",
    "settings.claude.polling.help": "Limit hesabın tüm Claude Code oturumlarıyla ortaktır; bu yüzden 5 dakikadan sık asla sorulmaz, bir rate limit sorgulamayı 15 dakika durdurur.",
    "settings.claude.cost": "Maliyet (ccusage)",
    "settings.claude.cost.path": "ccusage yolu",
    "settings.claude.cost.path.prompt": "Otomatik bul (Homebrew, npm, bun, npx)",
    "settings.claude.cost.choose": "Seç…",
    "settings.claude.cost.help": "Token, blok ve hızı uygulama oturum loglarından kendisi sayar. ccusage yalnızca günü fiyatlar: çevrimdışı çalışır, sürüm ccusage@20'ye sabittir. `brew install ccusage` ya da `npm i -g ccusage` ile kurun.",
    "settings.claude.advanced": "Gelişmiş",
    "settings.claude.configDir": "Claude yapılandırma dizini",
    "settings.claude.configDir.prompt": "~/.claude ya da $CLAUDE_CONFIG_DIR",
    "settings.claude.configDir.help": "Claude Code'un kimlik bilgilerini ve oturum loglarını tuttuğu yer. Değiştirmek modülü yeniden başlatır.",
    "settings.claude.auth.ok": "Giriş yapılmış",
    "settings.claude.auth.signedOut": "Giriş yapılmamış",
    "settings.claude.auth.signedOut.help": "Terminal'de `claude` çalıştırıp giriş yapın; çentik saniyeler içinde algılar.",
    "settings.claude.auth.expired": "Token süresi dolmuş",
    "settings.claude.auth.expired.help": "Herhangi bir `claude` komutu yeniler.",
    "settings.claude.auth.reauth": "Yeniden giriş gerekiyor",
    "settings.claude.auth.reauth.help": "`claude /login` çalıştırın.",
    "settings.claude.auth.rateLimited": "Rate limit",
    "settings.claude.auth.rateLimited.help": "Sorgulama %@ yeniden başlar.",
    "settings.claude.auth.unreachable": "Anthropic'e ulaşılamıyor",
    "settings.claude.cost.unknown": "ccusage aranıyor…",
    "settings.claude.cost.ready": "ccusage bulundu",
    "settings.claude.cost.notInstalled": "ccusage kurulu değil",
    "settings.claude.cost.notInstalled.help": "Yalnızca dolar tutarı gizli kalır; token, blok ve hız loglardan okunur.",
    "settings.claude.cost.failed": "ccusage başarısız",
    "settings.claude.cost.choose.message": "ccusage çalıştırılabilir dosyasını seçin",
    # Setup
    "settings.setup.intro": "MyNotch yalnızca diğer uygulamaların zaten bildiğini gösterir. Her satır bir izin ya da giriş; çentik yeşil olanlarla çalışır.",
    "settings.setup.players": "Oynatıcılar", "settings.setup.claude": "Claude Code", "settings.setup.system": "Sistem",
    "settings.setup.close": "Kapat", "settings.setup.done": "Bitti",
    "settings.setup.automation": "Spotify ve Müzik'i denetle",
    "settings.setup.automation.ok": "İzin verildi. Oynatma, kapak ve şarkı sözleri çalışır.",
    "settings.setup.automation.todo": "macOS bir oynatıcı ilk kez çalışırken sorar. Reddettiyseniz Otomasyon altında MyNotch'a izin verin.",
    "settings.setup.spotify": "Spotify kitaplığı (isteğe bağlı)",
    "settings.setup.spotify.ok": "Bağlı. Kalp kitaplığınızı gösterir ve değiştirir.",
    "settings.setup.spotify.todo": "Oynatıcıdaki kalbin parça kaydetmesini sağlar. Ücretsiz bir Spotify geliştirici uygulaması gerekir.",
    "settings.setup.goTo.media": "Medya'da ayarla…",
    "settings.setup.signIn": "Claude Code girişi",
    "settings.setup.signIn.ok": "Giriş yapılmış. Limitler birkaç dakikada bir Anthropic'ten okunur.",
    "settings.setup.signIn.todo": "Terminal'de `claude` çalıştırıp giriş yapın. MyNotch CLI'ın token'ını okur; kendisi asla saklamaz.",
    "settings.setup.logs": "Oturum logları",
    "settings.setup.logs.ok": "Bulundu. Nabız ve bugünün blokları buradan gelir.",
    "settings.setup.logs.todo": "Bu Mac'teki ilk Claude Code oturumundan sonra oluşur.",
    "settings.setup.ccusage": "Maliyet (isteğe bağlı)",
    "settings.setup.ccusage.ok": "ccusage bulundu. Bugünkü harcama kartta görünür.",
    "settings.setup.ccusage.todo": "Token ve bloklar onsuz da çalışır; bugünkü harcamayı görmek için ccusage kurun (`brew install ccusage`). Çevrimdışı çalışır.",
    "settings.setup.goTo.claude": "Claude'da ayarla…",
    "settings.setup.login": "Oturum açılışında başlat (isteğe bağlı)",
    "settings.setup.login.todo": "Yeniden başlatmadan sonra çentik yerinde olsun diye açın.",
    "settings.setup.login.enable": "Aç",
    # About
    "settings.about.version": "Sürüm %@",
    "settings.about.tagline": "Çentik canlı bir yüzey: çalan parça, şarkı sözleri ve Claude Code, bir hover uzakta.",
    "settings.about.network": "Bu Mac'ten dışarı ne gidiyor",
    "settings.about.network.lrclib": "Şarkı sözleri için çalan parçanın sanatçısı, adı, albümü ve süresi — yalnızca sözler açıkken.",
    "settings.about.network.spotify": "Kalbi okumak ya da değiştirmek için çalan parçanın kimliği — yalnızca hesabınızı bağladıktan sonra.",
    "settings.about.network.anthropic": "Her sorgulama aralığında Claude Code token'ıyla tek bir kullanım isteği; token CLI'ın Keychain kaydından okunur — asla yazılmaz, yenilenmez ya da loglanmaz.",
    "settings.about.network.none": "Başka hiçbir şey: analitik yok, çökme raporu yok.",
    "settings.about.credits": "Uyarlandığı kaynaklar",
    "settings.about.credits.help": "Uyarlanan her dosya kaynağını belirtir; lisans metinleri THIRD_PARTY_LICENSES.md içinde.",
    "settings.about.diagnostics": "Tanılama",
    "settings.about.logs": "Canlı log",
    "settings.about.debugPreview": "Debug Preview'ı aç",
    # Menu bar
    "menu.settings": "Ayarlar…", "menu.debugPreview": "Debug Preview", "menu.quit": "MyNotch'tan Çık",
    "menu.checkForUpdates": "Güncellemeleri Denetle…",
    "menu.updateAvailable": "%@ sürümüne güncelle…",
    "settings.about.releases": "Sürüm notları",
    "settings.about.network.github": "Güncelleme akışı (bu projenin deposundaki appcast.xml), günde bir, yalnızca uygulama ve macOS sürümüyle — Genel'deki anahtarla kapanır.",
    "settings.general.updates": "Güncellemeler",
    "settings.general.updates.enabled": "Güncellemeleri günde bir denetle",
    "settings.general.updates.help": "Projenin GitHub deposundaki appcast okunur; yalnızca uygulama ve macOS sürümü gider. Yeni sürüm notlarıyla önerilir ve yalnızca sen onaylayınca kurulur. Menü barındaki \"Güncellemeleri Denetle…\" her durumda çalışır.",
    "settings.tab.shelf": "Raf",
    "settings.shelf.missing": "Raf modülü kayıtlı değil.",
    "settings.shelf.status": "Raftakiler",
    "settings.shelf.empty": "Rafta bir şey yok",
    "settings.shelf.count.one": "1 dosya · %@",
    "settings.shelf.count.many": "%1$lld dosya · %2$@",
    "settings.shelf.error": "Son dosya işlemi başarısız oldu",
    "settings.shelf.reveal": "Finder'da Göster",
    "settings.shelf.clear": "Rafı boşalt",
    "settings.shelf.status.help": "Bırakma dosyayı kopyalar; özgün dosya yerinde kalır. Rafı boşaltmak yalnızca kopyaları siler.",
    "settings.shelf.keep": "Saklama",
    "settings.shelf.keep.picker": "Kopyaları sakla",
    "settings.shelf.keep.help": "Süresi dolan kopyalar raf yüklenirken ya da yeni bir dosya bırakılınca gider; zamanlayıcı yok. Dosyayı karttan dışarı sürüklemek kopyayı öteki uygulamaya verir; kaldırmak için öğeye Option ile dokun ya da ✕'e bas.",
    "settings.setup.shelf": "Raf (isteğe bağlı)",
    "settings.setup.shelf.todo": "Bir dosyayı çentiğe sürükle: açılır, bir süre kopyasını tutar ve AirDrop'la gönderebilir.",
    "settings.setup.shelf.ok": "Rafta dosyalar var. Kopyalar Application Support'ta durur ve kendiliğinden süresi dolar.",
    "settings.setup.shelf.open": "Raf ayarları…",
    "module.shelf": "Raf",
    "settings.modules.shelf.summary": "Dosyaları çentiğe sürükle: bir süre kopyası kalır, sonra AirDrop'la gönder ya da başka yere sürükle.",
    "shelf.airdrop": "AirDrop",
    "shelf.empty": "Dosyaları çentiğe bırak",
    "shelf.empty.forever": "Kopyalar sen kaldırana kadar durur.",
    "shelf.empty.keep": "Kopyalar %@ durur, sonra kendiliğinden gider.",
    "shelf.explain.airdrop.empty": "Doğrudan AirDrop'a göndermek için dosyayı buraya bırak; sonra dokununca raftaki her şeyi gönderir.",
    "shelf.explain.airdrop": "Raftaki tüm dosyaları AirDrop'la gönderir. Yalnızca birini göndermek için dosyayı bu tarafa bırak.",
    "shelf.explain.hint": "Bir dosyayı çentiğe sürükle: açılır, kopyasını burada tutar ve sonra başka bir uygulamaya sürüklemene izin verir.",
    "shelf.explain.item": "%1$@ · dokun aç, sürükle taşı, ✕ kaldır. %2$@ gider.",
    "shelf.explain.item.forever": "%@ · dokun aç, sürükle taşı, ✕ kaldır.",
    "settings.media.generic": "Diğer oynatıcılar",
    "settings.media.generic.enabled": "Mac'te ne çalıyorsa göster",
    "settings.media.generic.recheck": "Yeniden test et",
    "settings.media.generic.help": "Safari, Chrome, IINA, podcast uygulamaları — Now Playing'e yazan her şey. Paketlenmiş mediaremote-adapter'ı kullanır: perl, Apple'ın özel bir framework'ünü ayrı bir süreçte yükler; bir macOS güncellemesi bunu kırabilir. Sağlık kontrolü sürüm başına bir kez çalışır, kırılırsa çentik Spotify ve Müzik'e döner. Bu Mac'ten hiçbir şey çıkmaz.",
    "settings.media.generic.checking": "Adaptör denetleniyor…",
    "settings.media.generic.off": "Kapalı",
    "settings.media.generic.idle": "Dinliyor — başka yerde çalan yok",
    "settings.media.generic.playing": "%@ izleniyor",
    "settings.media.generic.ready": "Adaptör çalışıyor; kullanmak için anahtarı aç",
    "settings.media.generic.missing": "Bu derlemede adaptör paketlenmemiş",
    "settings.media.generic.testFailed": "Adaptörün kendi testi çalıştırılamadı",
    "settings.media.generic.noData": "macOS adaptörün Now Playing'i okumasına artık izin vermiyor",
    "settings.media.generic.broken": "Adaptör durdu (çıkış %lld); Spotify ve Müzik çalışmaya devam eder",
    "settings.media.generic.timedOut": "Kendi testi zaman aşımına uğradı",
    "media.generic.name": "Şimdi Çalıyor",
    "settings.media.visualizer": "Seviye ölçer",
    "settings.media.visualizer.enabled": "Çubuklar müziğe göre hareket etsin",
    "settings.media.visualizer.help": "Mac'in çaldığı sesi dinler (macOS 14.2 ve sonrası) ve uygulama içinde altı bant seviyesine indirger; ses saklanmaz, gönderilmez. macOS sistem sesi kaydı iznini bir kez sorar. Kapalıyken çubuklar kendi ritmiyle oynar.",
    "settings.media.visualizer.idle": "Müzik bekleniyor",
    "settings.media.visualizer.off": "Kapalı — çubuklar kendi başına oynar",
    "settings.media.visualizer.unsupported": "macOS 14.2 ya da sonrası gerekir",
    "settings.media.visualizer.starting": "Tap başlatılıyor…",
    "settings.media.visualizer.running": "Sesi izliyor",
    "settings.media.visualizer.silent": "Hiçbir şey duyulmuyor — Gizlilik ve Güvenlik → Ekran ve Sistem Sesi Kaydı altında MyNotch'a izin ver",
    "settings.media.visualizer.failed": "Tap başlatılamadı (%lld)",
    # Media module
    "media.favorite.unsupported": "%@ başka uygulamaların parça kaydetmesine izin vermiyor",
    "media.favorite.nothingPlaying": "Hiçbir şey çalmıyor",
    "media.permission.title": "Otomasyon izni gerekiyor",
    "media.permission.path": "Sistem Ayarları → Gizlilik ve Güvenlik → Otomasyon → MyNotch",
    "media.idle.start": "Spotify ya da Müzik'i başlatın",
    "media.lyrics.loading": "Şarkı sözleri…",
    "media.lyrics.nudge.help": "Bu şarkının söz zamanlaması — sıfırlamak için tıklayın",
    "media.favorite.remove": "Favorilerden çıkar",
    "media.favorite.add": "Favorilere ekle",
    "media.idle.nothingIn": "%@ uygulamasında bir şey çalmıyor",
    "media.idle.nothing": "Bir şey çalmıyor",
    "media.lyrics.earlier": "Sözleri daha erken göster",
    "media.lyrics.later": "Sözleri daha geç göster",
    "spotify.error.noClientID": "Spotify client ID ayarlanmamış",
    # Battery module
    "module.battery": "Pil",
    "settings.tab.battery": "Pil",
    "settings.modules.battery.summary": "Şarj ve düşük pil bildirimleri, gerektiğinde bir gösterge.",
    "settings.battery.missing": "Pil modülü kayıtlı değil.",
    "settings.battery.status": "Durum",
    "settings.battery.none": "Dahili pil yok",
    "settings.battery.none.help": "Modül bu Mac'te boşta kalır.",
    "settings.battery.alerts": "Uyarılar",
    "settings.battery.alerts.enabled": "Adaptör takılıp çıkarılınca ya da pil azalınca açılır bildirim",
    "settings.battery.alerts.low": "Düşük eşiği",
    "settings.battery.alerts.critical": "Kritik eşik",
    "settings.battery.alerts.reset": "Eşikleri sıfırla",
    "settings.battery.alerts.help": "Her seviye bir boşalmada bir kez duyurulur; şarja takmak yeniden silahlandırır. Çentikteki gösterge aynı noktalarda turuncuya ve kırmızıya döner.",
    "battery.none": "Bu Mac'te pil yok",
    "battery.estimate.pending": "Hesaplanıyor…",
    "battery.lowPower.on": "Düşük Güç Modu",
    "battery.lowPower.off": "Tam güç",
    "battery.explain.estimating": "macOS bir tahmine bağlanmak için birkaç dakika düzenli kullanım ister.",
    # Pomodoro module
    "module.pomodoro": "Pomodoro",
    "settings.tab.pomodoro": "Pomodoro",
    "settings.modules.pomodoro.summary": "Odak zamanlayıcısı: çentiğin yanında halka, kartta denetimler, fazlar arasında zil.",
    "settings.pomodoro.status": "Şimdi",
    "settings.pomodoro.status.done": "%lld odak bloğu tamamlandı",
    "settings.pomodoro.lengths": "Süreler",
    "settings.pomodoro.work": "Odak",
    "settings.pomodoro.break": "Kısa mola",
    "settings.pomodoro.longBreak": "Uzun mola",
    "settings.pomodoro.every": "Uzun mola sıklığı",
    "settings.pomodoro.every.value": "%lld blokta bir",
    "settings.pomodoro.behaviour": "Fazlar arasında",
    "settings.pomodoro.autoStart": "Sonraki fazı otomatik başlat",
    "settings.pomodoro.sound": "Faz bitince zil çal",
    "settings.pomodoro.reset": "25 / 5 / 15'e dön",
    "settings.pomodoro.help": "Zamanlayıcı çentikte yaşar: halkayı görmek için üzerine gel, başlatmak, duraklatmak, atlamak ya da sıfırlamak için karta dokun. Çalışan döngü yeniden açılışta devam eder.",
    "pomodoro.cycles.caption": "%lld tamam",
    "pomodoro.explain.phase": "odak blokları ve molalar sırayla gelir; süreler Ayarlar'da.",
    "pomodoro.explain.controls": "Başlat ya da duraklat, sonraki faza atla ya da tüm döngüyü sıfırla.",
    # Calendar module
    "module.calendar": "Takvim",
    "settings.tab.calendar": "Takvim",
    "settings.modules.calendar.summary": "Sıradaki toplantı: yaklaşınca geri sayım, başlamadan önce bildirim, Katıl düğmesi.",
    "settings.calendar.missing": "Takvim modülü kayıtlı değil.",
    "settings.calendar.access": "Erişim",
    "settings.calendar.grant": "Erişim ver…",
    "settings.calendar.openPrivacy": "Gizlilik Ayarları'nı aç…",
    "settings.calendar.refresh": "Yenile",
    "settings.calendar.access.help": "Salt okuma. Etkinlikler bu Mac'ten çıkmaz; çentik sıradaki birkaçını ve toplantı bağlantılarını gösterir.",
    "settings.calendar.timing": "Zamanlama",
    "settings.calendar.lead": "Geri sayımı göster",
    "settings.calendar.lead.value": "%lld dk önce",
    "settings.calendar.alerts": "Başlamadan beş dakika önce ve başlarken bildirim",
    "settings.calendar.calendars": "Takvimler",
    "settings.calendar.calendars.none": "Takvim seçmek için erişim ver; o zamana kadar her takvim sayılır.",
    "settings.calendar.calendars.help": "Hiçbiri seçili değilken her takvim sayılır.",
    "settings.calendar.access.ok": "İzin verildi",
    "settings.calendar.access.notAsked": "Henüz sorulmadı",
    "settings.calendar.access.denied": "Reddedildi — Takvimler altında MyNotch'a izin ver",
    "settings.calendar.access.restricted": "Bir profil tarafından kısıtlanmış",
    "settings.setup.calendarSection": "Takvim",
    "settings.setup.calendar": "Takvim (isteğe bağlı)",
    "settings.setup.calendar.ok": "İzin verildi. Sıradaki toplantı yaklaşınca çentikte görünür.",
    "settings.setup.calendar.todo": "İsteğe bağlı. Çentiğin sıradaki toplantıya geri saymasını ve bağlantısını açmasını sağlar.",
    "settings.setup.calendar.denied": "Reddedildi. Gizlilik ve Güvenlik → Takvimler altında MyNotch'a izin ver.",
    "calendar.noAccess": "Takvim erişimi gerekiyor",
    "calendar.noAccess.help": "MyNotch Ayarları → Takvim'den izin ver.",
    "calendar.empty": "Bugün toplantı kalmadı",
    "calendar.join": "Katıl",
}

# Keys used through `String(localized:defaultValue:bundle:)` in the pure rules (interpolated
# text needs the `bundle:` form); they are not scanned from code, only merged.
EXTRA_TR = {
    "shelf.keep.forever": "Kaldırılana kadar",
    "shelf.keep.hour": "1 saat",
    "shelf.keep.hours12": "12 saat",
    "shelf.keep.day": "1 gün",
    "shelf.keep.days2": "2 gün",
    "shelf.keep.week": "1 hafta",
    "shelf.event.dropped.one": "Rafta 1 dosya",
    "shelf.event.dropped.many": "Rafta %lld dosya",
    "shelf.event.airdrop.one": "1 dosya AirDrop'la gönderiliyor",
    "shelf.event.airdrop.many": "%lld dosya AirDrop'la gönderiliyor",
    "battery.status.full": "Tamamen dolu",
    "battery.status.charging": "Şarj oluyor",
    "battery.status.plugged": "Prizde, şarj olmuyor",
    "battery.status.onBattery": "Pilde",
    "battery.estimate.toFull": "%@ sonra dolar",
    "battery.estimate.left": "%@ kaldı",
    "battery.event.pluggedIn": "Şarj oluyor",
    "battery.event.unplugged": "Pilde",
    "battery.event.low": "Pil azaldı",
    "battery.event.critical": "Pil kritik",
    "battery.event.critical.detail": "%@ — hemen şarja tak",
    "battery.event.full": "Tamamen dolu",
    "battery.event.lowPowerOn": "Düşük Güç Modu açık",
    "battery.event.lowPowerOff": "Düşük Güç Modu kapalı",
    "battery.explain.gauge": "%1$@ dolu. Gösterge %%%2$lld'de turuncuya, %%%3$lld'de kırmızıya döner; ikisi de Ayarlar'da.",
    "battery.explain.charging": "Adaptörden şarj alıyor. Tahmin macOS'un kendi tahmini, yüke göre değişir.",
    "battery.explain.plugged": "Prizde. macOS pili korumak için şarjı burada tutuyor.",
    "battery.explain.onBattery": "Pille çalışıyor. Kalan süre macOS'un mevcut tüketimden tahmini.",
    "battery.explain.lowPowerOn": "Düşük Güç Modu açık: daha yavaş işlemci, daha loş ekran, daha uzun süre.",
    "battery.explain.lowPowerOff": "Düşük Güç Modu kapalı. Saatlere ihtiyacın olduğunda Sistem Ayarları → Pil'den aç.",
    "pomodoro.phase.idle": "Odaklanmaya hazır",
    "pomodoro.phase.work": "Odak",
    "pomodoro.phase.shortBreak": "Kısa mola",
    "pomodoro.phase.longBreak": "Uzun mola",
    "pomodoro.event.workDone": "Odak bitti",
    "pomodoro.event.breakNext": "%lld dakika mola",
    "pomodoro.event.breakOver": "Mola bitti",
    "pomodoro.event.workNext": "%lld dakika odak",
    "pomodoro.explain.cycle": "%1$lld odak %2$@ tamamlandı. Her %3$lld blokta mola %5$lld yerine %4$lld dakika.",
    "pomodoro.explain.running": "Halka faz bittikçe boşalır; kendi kendine akar, izlemek gerekmez.",
    "pomodoro.explain.paused": "Duraklatıldı. Başlat buradan devam eder; Sıfırla döngüyü atar.",
    "pomodoro.explain.idle": "%1$lld dakika odak, sonra %2$lld dakikalık mola. Başlat ilk bloğu açar.",
    "calendar.now": "şimdi",
    "calendar.event.fiveMinutes": "%@ 5 dakika sonra",
    "calendar.event.starting": "%@ başlıyor",
    "calendar.provider.other": "Görüntülü görüşme",
    "calendar.explain.rail": "Sıradaki %1$lld etkinlik %2$lld saatlik bir ray üzerinde, takvimlerinin renginde; işaret şu an.",
    "calendar.explain.underway": "%1$@'dan beri sürüyor; %2$@'da bitiyor.",
    "calendar.explain.next": "%@ sonra başlıyor. Beş dakika önce ve başlarken bildirim gelir.",
    "calendar.explain.join": "Davetiyedeki %@ bağlantısını tarayıcıda ya da uygulamada açar.",
}


def main() -> int:
    keys: dict[str, str] = {}
    for path in SOURCES:
        for key, default in CALL.findall(path.read_text()):
            keys.setdefault(key, default)

    catalog = json.loads(CATALOG.read_text())
    strings = catalog["strings"]
    added = 0
    for key in sorted(keys):
        translation = TR.get(key)
        if translation is None:
            continue
        entry = strings.setdefault(key, {})
        localizations = entry.setdefault("localizations", {})
        if "tr" not in localizations:
            localizations["tr"] = {"stringUnit": {"state": "translated", "value": translation}}
            added += 1

    for key, translation in EXTRA_TR.items():
        entry = strings.setdefault(key, {})
        localizations = entry.setdefault("localizations", {})
        if "tr" not in localizations:
            localizations["tr"] = {"stringUnit": {"state": "translated", "value": translation}}
            added += 1

    missing = sorted(k for k in keys if k not in TR)
    unused = sorted(k for k in TR if k not in keys)
    CATALOG.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    print(f"{len(keys)} keys in code, {added} translations added, {len(strings)} entries in catalog")
    if missing:
        print("MISSING tr:", *missing, sep="\n  ")
    if unused:
        print("UNUSED in code:", *unused, sep="\n  ")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
